FROM debian:bookworm-slim

LABEL description="Development environment for bemanitools"

# mingw-w64-gcc has 32-bit and 64-bit toolchains
RUN apt-get update && apt-get install -y --no-install-recommends \
    mingw-w64 \
    mingw-w64-common \
    make \
    zip \
    git \
    ca-certificates \
    clang-format \
    python3-pip \
 && rm -rf /var/lib/apt/lists/*

RUN git config --global --add safe.directory /bemanitools

RUN pip3 install --break-system-packages mdformat

RUN mkdir /bemanitools
WORKDIR /bemanitools

ENV SHELL /bin/bash