FROM debian:bookworm-slim

LABEL description="Build environment for bemanitools"

# mingw-w64-gcc has 32-bit and 64-bit toolchains
RUN apt-get update && apt-get install -y --no-install-recommends \
    mingw-w64 \
    mingw-w64-common \
    make \
    zip \
    git \
    ca-certificates \
 && rm -rf /var/lib/apt/lists/*

RUN git config --global --add safe.directory /bemanitools

RUN mkdir /bemanitools
WORKDIR /bemanitools

ENTRYPOINT [ \
    "/bin/sh", \
    "-c" , \
    "cd /bemanitools && \
    make" ]