name: "Build kpmhook"

on:
  push:
    branches:
      - master
      - kpm
      - "kpm*"
  pull_request:
    branches:
      - master
      - kpm
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup MSVC x86"
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: "Build KPM Toolchain"
        shell: cmd
        run: |
          call build_kpmhook_msvc.bat

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: kpmhook-${{ github.sha }}
          retention-days: 90
          if-no-files-found: "error"
          path: |
            build/bin/geninput.dll
            build/bin/kpmio.dll
            build/bin/kpmhook.dll
            build/bin/eamhook.dll
            build/bin/config.exe
