name: "Build kpmhook"

on:
  push:
    branches:
      - master
      - kpm
      - "kpm*"
  pull_request:
    branches:
      - master
      - kpm
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup MSVC x86"
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: "Build & Package KPM Release"
        shell: cmd
        run: |
          call package_kpm.bat

      - name: "Upload Release Package"
        uses: actions/upload-artifact@v4
        with:
          name: bemanitools-kpm-${{ github.sha }}
          retention-days: 90
          if-no-files-found: "error"
          path: build/bemanitools-kpm.zip
